name: Build MkDocs

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in second repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/Yldales/isla-nycta-rules/dispatches \
          -d '{"event_type": "isla_nycta_data_updated"}'